### ISSUE TITLE
server_version field

### ISSUE THREAD

**Issue by jklmnn** [defgsus/ParkAPI2#10]
I noticed that you set the `server_version` field to `0.3.666` which is identical to the current ParkAPI implementation. Clients should not depend on this field. It's intended to provide information about the current implementation that serves the API. We're currently using the format `major.minor.commit_count`. The goal of this field is to make different versions of an implementation distinguishable, the easiest way to do it would be to use the git commit id. Since we're now having two implementations it may make sense to add a `server_name` field that names the implementation (e.g. `ParkAPI2` in your case).

**Comment by defgsus** [comment]
I see. 

Like this, if understood correctly?
```
{
  "api_version": "1.0",
  "server_version": "0.1.abcdef12",
  "server_name": "ParkAPI2",
  ...
}
```

**Comment by jklmnn** [comment]
Yes, that's the idea. The `api_version` is what is relevant for clients. The `server_version` and `server_name` are more or less just meta data that we add for clearness.

**Comment by defgsus** [comment]
Turns out there is this `reference` entry already. I think that is descriptive enough. Looks like this now: 
```
{
  "api_version": "1.0",
  "server_version": "0.1.abcdef12",
  "reference": "https://github.com/ParkenDD/ParkAPI2",
  ...
}
```
