### ISSUE TITLE
Fehlende Lizenz

### ISSUE THREAD

**Issue by the-infinity** [defgsus/ParkAPI2#13]
Mögt ihr euch auf eine Lizenz festlegen? Ist es wie die v1 auch eine MIT Lizenz? Danke!

**Comment by defgsus** [comment]
Hi Ernesto, danke für den Hinweis! 
Kein Problem mit MIT Lizenz. Habs gleich eingefügt. 

@jklmnn , @kiliankoe , passt das für euch?

**Comment by jklmnn** [comment]
@defgsus du hast den Code geschrieben, du bist der einzige der die Lizenz bestimmen darf ;)
Aber ja, passt für mich. Die alte ParkAPI hat auch MIT, es ist ganz gut, wenn das konsistent ist, denke ich.

**Comment by the-infinity** [comment]
Danke! Das gilt dann auch für https://github.com/ParkenDD/ParkAPI2-sources ?

**Comment by defgsus** [comment]
Gemacht ;)
