### ISSUE TITLE
moving the repository

### ISSUE THREAD

**Issue by defgsus** [defgsus/ParkAPI2#7]
Hi @jklmnn and @kiliankoe,

so let's move the repository out of my personal space. Without really knowing all the projects i'd vote for https://github.com/ParkenDD. Unless someone argues that https://github.com/ParkAPI is a better place. I just like the *DD* (good friends and memories there). 

In the process i will also extract the scrapers into an own repository which can then be *git submoduled* into the main repo.

So it will actually be three repos:
- **ParkAPI2** is the server and scraping *manager*. 
- **ParkAPIScraper** would be the base repository for all scraper contributors, including the whole scraping backend and an example scraper.
- **???** will be a fork of **ParkAPIScraper** containing all scrapers that are currently maintained (from our side). I just don't have a good name a.t.m. Still too early in the morning ;) 

Whaddya say?

**Comment by kiliankoe** [comment]
Sounds great to me 👍 I just invited you to the ParkenDD org. Btw, there was another try at renaming (and in the process rewriting/-structuring) the project at https://github.com/OpenParkingApp, just for completeness 😄 But if you want to stick with the name ParkenDD, that's just as good!

The proposed repo structure also sounds good to me.

**Comment by defgsus** [comment]
Okay. So any good name proposal for the **own** scrapers repo?
Maybe just `ParkAPIScapers`. Although the name is very similar to the scraper root repo.  
Maybe something like `ParkAPI-maintained-scrapers`?

Basically it means: Any issues regarding the API should be opened in `ParkAPI2`. Issues about scrapers not working or to-be-updated goes to the `ParkAPI-maintained-scrapers`. 

*Third-party* scrapers might have their own repositories, but i think issues will potentially be created in our scrapers repo. 

It would also be an option to accept pull requests in our scrapers repo, letting contributors add scrapers there directly. Then, if someone wants to add the whole of Switzerland that might deserve creating a new scrapers repository.

**Comment by kiliankoe** [comment]
What about datasources instead of scrapers? Not all of them rely on scraping to get their data anyways.

**Comment by jklmnn** [comment]
Thanks for moving the repository! I think we should maintain our datasources in a separate repository where we also accept pull requests. But we should also support adding datasources via third party repositories.

**Comment by defgsus** [comment]
@jklmnn, yes, that's what i think too. 

i've added some unittests for the API endpoints today, including geo-queries on the database. However, testing scrapers/sources is not reliable using web requests. Maybe i'll add some convenience code to the scraper backend to automatically create unittests from web response data, to create tests like in the original ParkAPI.
